[tool.poetry]
name = "danea-automation"
version = "0.2.1"
description = ""
authors = ["Luca Salvarani <lucasalvarani99@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]
repository = "https://github.com/LukeSavefrogs/danea-easyfatt"


[tool.poetry.dependencies]
python = ">=3.7, <3.12"
rich = "^13.0.1"
xmltodict = "^0.13.0"
requests = "^2.28.2"
toml = "^0.10.2"
packaging = "^23.0"


[tool.poetry.group.dev.dependencies]
gitpython = "^3.1.30"
pyinstaller = "^5.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
build = "scripts.build:main"
release = "scripts.release:main"