[tool.poetry]
name = "danea-automation"
version = "0.4.2a0"
description = ""
authors = ["Luca Salvarani <lucasalvarani99@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]
repository = "https://github.com/LukeSavefrogs/danea-easyfatt"


[tool.poetry.dependencies]
python = ">=3.8, <3.12"
rich = "^13.0.1"
xmltodict = "^0.13.0"
requests = "^2.28.2"
toml = "^0.10.2"
packaging = "^23.0"
pandas = "^1.5.3"
openpyxl = "^3.0.10"
pint = "^0.20.1"


[tool.poetry.group.dev.dependencies]
gitpython = "^3.1.30"
pyinstaller = "^5.7.0"
poethepoet = "^0.18.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
build = "scripts.build:main"
release = "scripts.release:main"


[tool.poe.tasks.docs]
sequence = [
	{script  = "os:system('bundle exec jekyll clean')"},
	{script  = "os:system('bundle exec jekyll serve --livereload --open-url --strict_front_matter --trace')"}
]
help = "Lancia il server LiveReload di Jekyll"