[tool.poetry]
name = "danea-automation"
version = "0.1.5a0"
description = ""
authors = ["Luca Salvarani <lucasalvarani99@gmail.com>"]
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = ">=3.7, <3.12"
rich = "^13.0.1"
xmltodict = "^0.13.0"


[tool.poetry.group.dev.dependencies]
gitpython = "^3.1.30"
pyinstaller = "^5.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
