name: Check Python code formatting

on:
  push:
    paths:
      - '**.py'
      - '**.pyw'
      - '**.pyi'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: "📦 Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "🐍 Install Python"
        uses: actions/setup-python@v5
        
      - name: "🔍 Install dependencies"
        run: uv sync --group dev

      - name: "🖤 Check code formatting with Black"
        run: uv run black --check ./src/