name: Check Python code formatting

on:
  push:
    paths:
      - '**.py'
      - '**.pyw'
      - '**.pyi'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: "📜 Install Poetry"
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: 2.3.2

      - name: "🐍 Install Python"
        uses: actions/setup-python@v6
        with:
          cache: 'poetry'
          python-version: '3.13'
        
      - name: "🔍 Install dependencies"
        run: poetry install --with dev

      - name: "🖤 Check code formatting with Black"
        run: poetry run black --check ./src/
