name: "Run tests"

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: "🛒 Checkout repository"
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0

      - name: "📦 Install uv"
        uses: astral-sh/setup-uv@v5

      - name: "🐍 Install Python"
        uses: actions/setup-python@v5

      - name: "🔍 Install dependencies"
        run: uv sync --group dev

      - name: "🧪 Run tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run poe test -- --verbose
