name: "Run tests"

on:
  push:
    paths-ignore:
      - '**.md'
  workflow_call:
  workflow_dispatch:

env:
  POETRY_VERSION: "1.4.2"

permissions:
  contents: write

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: "🛒 Checkout repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: "📜 Install Poetry"
        run: pipx install poetry

      - name: "🐍 Install Python"
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          cache-dependency-path: poetry.lock

      - name: "🔍 Install dependencies"
        run: poetry install --with dev

      - name: "🧪 Run tests"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run poe test -- --verbose
